databases:
  name: likdin
  databaseName: likdin
  user: likdin
  plan: free

services
  type: web
  name: likdin
  runtime: ruby 
  plan: free
  buildCommand: "./bin/render-build.sh"
  startCommand: "bundle exec rails server"
  envVars: 
    - key: DATABASE_URL
      fromDatabase:
        name: likdin
        property: connectionString
    - key: RAILS_MASTER_KEY
      sync:false- key: WEB_CONCURRENCY
      value: 2